"""empty message

Revision ID: 054db97b358c
Revises: None
Create Date: 2016-03-02 23:29:24.287063

"""

# revision identifiers, used by Alembic.
revision = '054db97b358c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('create_time', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'create_time')
    ### end Alembic commands ###
