"""empty message

Revision ID: 9a0fd1145ba4
Revises: 448cf8e4fcbd
Create Date: 2016-04-26 10:28:27.941932

"""

# revision identifiers, used by Alembic.
revision = '9a0fd1145ba4'
down_revision = '448cf8e4fcbd'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'groups_users', 'group', ['group_id'], ['id'])
    op.create_foreign_key(None, 'groups_users', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'post', 'user', ['user_id'], ['id'])
    op.drop_column('post', 'img_src')
    op.create_foreign_key(None, 'roles_users', 'role', ['role_id'], ['id'])
    op.create_foreign_key(None, 'roles_users', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user', 'group', ['own_group_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'roles_users', type_='foreignkey')
    op.drop_constraint(None, 'roles_users', type_='foreignkey')
    op.add_column('post', sa.Column('img_src', mysql.VARCHAR(length=512), nullable=True))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_constraint(None, 'groups_users', type_='foreignkey')
    op.drop_constraint(None, 'groups_users', type_='foreignkey')
    ### end Alembic commands ###
