"""empty message

Revision ID: fa83da1ebc7f
Revises: 9a0fd1145ba4
Create Date: 2016-04-26 11:30:26.867235

"""

# revision identifiers, used by Alembic.
revision = 'fa83da1ebc7f'
down_revision = '9a0fd1145ba4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'groups_users', 'group', ['group_id'], ['id'])
    op.create_foreign_key(None, 'groups_users', 'user', ['user_id'], ['id'])
    op.add_column('post', sa.Column('title', sa.String(length=256), nullable=True))
    op.add_column('post', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.drop_index('ix_post_create_time', table_name='post')
    op.create_foreign_key(None, 'post', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'roles_users', 'role', ['role_id'], ['id'])
    op.create_foreign_key(None, 'roles_users', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user', 'group', ['own_group_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'roles_users', type_='foreignkey')
    op.drop_constraint(None, 'roles_users', type_='foreignkey')
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_index('ix_post_create_time', 'post', ['create_time'], unique=False)
    op.drop_column('post', 'update_time')
    op.drop_column('post', 'title')
    op.drop_constraint(None, 'groups_users', type_='foreignkey')
    op.drop_constraint(None, 'groups_users', type_='foreignkey')
    ### end Alembic commands ###
